print("Welcome to the Band Name Generator")
user = input("What's the name of the city u grew up in?\n")
pet = input("what's your pet's name?\n")
print("Your band name could be " + user+""+pet)
print("from github")
